<?php

/**
 * @file
 * This module provides a block to display the countdown event module
 *
 * Author: Mahesh Sankhala
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @see https://www.drupal.org/documentation/help-text-standards
 *
 * @see hook_help()
 */
function countdown_event_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
//    case 'page_example_simple':
//      // Help text for the simple page registered for this path.
//      return t('This is help text for the simple page.');

    case 'help.page.countdown_event':
      // Help text for the admin section, using the module name in the path.
      // Return content of the module README.txt.
      return check_markup(file_get_contents(dirname(__FILE__) . "/README.txt"));
  }
}
